# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1, 2, 8, 10])

# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1, 4, 7, 19],
             [5, 2, 6, 11]])
# Create a 3-dimensional Numpy array using np.array()

a3 = np.array([[1, 4, 7, 19],
             [5, 2, 6, 11],
             [7, 1, 0, 3]])

a1, a2, a3

(array([ 1,  2,  8, 10]),
 array([[ 1,  4,  7, 19],
        [ 5,  2,  6, 11]]),
 array([[ 1,  4,  7, 19],
        [ 5,  2,  6, 11],
        [ 7,  1,  0,  3]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size

((4,), 1, dtype('int64'), 4)

In [13]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size

((2, 4), 2, dtype('int64'), 8)

In [14]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size

((3, 4), 2, dtype('int64'), 12)

In [21]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df_a1 = pd.DataFrame(a1)
df_a2 = pd.DataFrame(a2)
df_a3 = pd.DataFrame(a3)
df_a3



0  1  2   3
0  1  4  7  19
1  5  2  6  11
2  7  1  0   3

In [27]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), dtype = int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [29]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5_random = np.random.randint(10, size = (7, 2))
a5_random

array([[6, 4],
       [0, 1],
       [9, 0],
       [2, 1],
       [2, 7],
       [7, 7],
       [0, 9]])

In [42]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6_random_float = np.random.random_sample((3, 5))
a6_random_float

array([[0.61784999, 0.85555332, 0.93023817, 0.87644027, 0.83193358],
       [0.43244469, 0.5074469 , 0.23748937, 0.14073783, 0.23247629],
       [0.11150413, 0.97463041, 0.13110676, 0.10879196, 0.32233631]])

In [52]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7_random = np.random.randint(10, size=(4, 6))
a7_random

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [53]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a7_random = np.random.randint(10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(a7_random)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [55]:
# Find the 0'th index of the latest array you created
a7_random

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [57]:
a7_random[0][0]

8

In [60]:
# Get the first 2 rows of latest array you created
a7_random[1:]

array([[2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [63]:
# Get the first 2 rows of latest array you created
a7_random[:-1]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [68]:
# Get the first 2 values of the first 2 rows of the latest array
a7_random[:-1,:2]

array([[8, 0],
       [2, 4]])

In [75]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8_random = np.random.randint(10, size=(3, 5))
a9_ones = np.ones((3,5))

a8_random, a9_ones

(array([[4, 2, 7, 5, 2],
        [0, 2, 4, 2, 0],
        [4, 9, 6, 6, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [76]:
# Add the two arrays together
a8_random + a9_ones

array([[ 5.,  3.,  8.,  6.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.]])

In [80]:
# Create another array of ones of shape (5, 3)
a10_ones = np.ones((5,3))
a10_ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
# Try add the array of ones and the other most recent array together
a8_random + a10_ones.T

array([[ 5.,  3.,  8.,  6.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [81]:
# Create another array of ones of shape (3, 5)
a11_ones = np.ones((3,5))

In [82]:
# Subtract the new array of ones from the other most recent array
a8_random - a11_ones

array([[ 3.,  1.,  6.,  4.,  1.],
       [-1.,  1.,  3.,  1., -1.],
       [ 3.,  8.,  5.,  5.,  7.]])

In [85]:
# Multiply the ones array with the latest array
a12 = a11_ones * a8_random
a12

array([[4., 2., 7., 5., 2.],
       [0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.]])

In [86]:
# Take the latest array to the power of 2 using '**'
a12**2

array([[16.,  4., 49., 25.,  4.],
       [ 0.,  4., 16.,  4.,  0.],
       [16., 81., 36., 36., 64.]])

In [87]:
# Do the same thing with np.square()
np.square(a12)

array([[16.,  4., 49., 25.,  4.],
       [ 0.,  4., 16.,  4.,  0.],
       [16., 81., 36., 36., 64.]])

In [88]:
# Find the mean of the latest array using np.mean()
np.mean(a12)

4.066666666666666

In [89]:
# Find the maximum of the latest array using np.max()
np.max(a12)

9.0

In [91]:
# Find the minimum of the latest array using np.min()
np.min(a12)

0.0

In [92]:
# Find the standard deviation of the latest array
np.std(a12)

2.6699979192667715

In [93]:
# Find the variance of the latest array
np.var(a12)

7.12888888888889

In [94]:
# Reshape the latest array to (3, 5, 1)
a12.reshape(3, 5, 1)

array([[[4.],
        [2.],
        [7.],
        [5.],
        [2.]],

       [[0.],
        [2.],
        [4.],
        [2.],
        [0.]],

       [[4.],
        [9.],
        [6.],
        [6.],
        [8.]]])

In [95]:
# Transpose the latest array
a12.T
a12

array([[4., 2., 7., 5., 2.],
       [0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.]])

What does the transpose do?

In [98]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a13 = np.random.randint((3,3))
a14 = np.random.randint((3,2))
a13, a14

(array([2, 2]), array([1, 1]))

In [103]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(a13, a14)
dot_product

4

In [110]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a15 = np.random.randint(10, size=(4, 3))
a16 = np.random.randint(10, size=(4,3 ))
a15.shape, a16.shape

((4, 3), (4, 3))

In [112]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(a15, a16.T)
a15.shape, a16.T.shape
dot_product

array([[ 8, 38, 22, 12],
       [ 0, 28, 42, 49],
       [ 2, 13,  9,  7],
       [ 8, 65, 73, 72]])

It doesn't work. How would you fix it?

In [113]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


### Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [115]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a17 = np.random.randint(10, size=(4, 3))
a18 = np.random.randint(10, size=(4, 3))
a17, a18

(array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8],
        [5, 2, 3]]),
 array([[3, 2, 9],
        [2, 2, 3],
        [6, 3, 8],
        [0, 7, 6]]))

In [116]:
# Compare the two arrays with '>'
a17 > a18

array([[ True,  True, False],
       [ True, False,  True],
       [False, False, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [117]:
# Compare the two arrays with '>='
a17 >= a18

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False, False]])

In [118]:
# Find which elements of the first array are greater than 7
a17 > 7

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [119]:
# Which parts of each array are equal? (try using '==')
a17 == a18 

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [120]:
# Sort one of the arrays you just created in ascending order
a17.sort()
a17

array([[4, 5, 7],
       [1, 3, 5],
       [0, 5, 8],
       [2, 3, 5]])

In [125]:
# Sort the indexes of one of the arrays you just created
a17.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [124]:
# Find the index with the maximum value in one of the arrays you've created
a17.argmax()

8

In [126]:
# Find the index with the minimum value in one of the arrays you've created
a17.argmin()

6

In [127]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a17.argmin(axis=1)

array([0, 0, 0, 0])

In [128]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a17.argmin(axis=0)

array([2, 1, 1])

In [129]:
# Create an array of normally distributed random numbers
a19 = np.random.normal()
a19

-0.7832532923362371

In [130]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a20 = np.linspace(1, 100)
a20

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.